---
# file: roles/galera/tasks/install.yml
- name: Installing MariaDB Galera packages
  apt: name="{{ item }}"
    state=latest
    update_cache=yes
  with_items:
    - mariadb-server
    - xtrabackup
    - socat
    - python-mysqldb
    - percona-toolkit
  tags: galera-install
