---
# file: roles/galera/tasks/repos.yml
- include: repos/Debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - galera
    - galera-repo

- include: repos/CentOS.yml
  when: ansible_distribution == 'CentOS'
  tags:
    - galera
    - galera-repo
